GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTAyMTMyMjQsImV4cCI6MTY1MDIxNjgyNCwiYXVkIjoiNjI1YzFlNTliMmFjZDc1ODc2MmJiYmE5IiwiaXNzIjoiYml4YmFzZS5jb20ifQ.6RlJRkPjdFwFaNd2ghFr2pwnBCAerX-A7zsyxJ3Yzj0

### register
POST http://localhost:3000/v1/auth/register
Content-Type: application/json

{
    "email":"chyluy@gail.co",
    "password":"123456789",
    "fullName":"ketem one",
    "mobile":"07057001119"
}


### login
POST http://localhost:3000/v1/auth/login
Content-Type: application/json

{
    "email":"chyluy@gail.co",
    "password":"123456789"
}

 
### refresh token
POST http://localhost:3000/v1/auth/reftk
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTAyOTI1MjMsImV4cCI6MTY4MTg1MDEyMywiYXVkIjoiNjI1YzFlNTliMmFjZDc1ODc2MmJiYmE5IiwiaXNzIjoiYml4YmFzZS5jb20ifQ.xXjubNeSpyj2mb0OGnj8fqKgdT0Cy-9dbtIOXFUtKcg"
}



### Logout
POST http://localhost:3000/v1/auth/logout
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTAyOTI4NTgsImV4cCI6MTY4MTg1MDQ1OCwiYXVkIjoiNjI1YzFlNTliMmFjZDc1ODc2MmJiYmE5IiwiaXNzIjoiYml4YmFzZS5jb20ifQ.L7WrJ3vW1LnWqONEzfRhwVT4x6sZeuhzX_sjP4-IUCA"
}
