GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTA2OTA3MDUsImV4cCI6MTY1MDY5NDMwNSwiYXVkIjoiNjI2MTU0ZjM4ZjRlNzUwOGI0YzNmOGU0IiwiaXNzIjoiYml4YmFzZS5jb20ifQ.yyoNYwO1RsF700ICZM3MLQUWtOXzMbb2x7BewDRIWK8


### user
GET http://localhost:3000/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTA1NDU5MDcsImV4cCI6MTY1MDU0OTUwNywiYXVkIjoiNjI2MTU0ZjM4ZjRlNzUwOGI0YzNmOGU0IiwiaXNzIjoiYml4YmFzZS5jb20ifQ.adkY3De3XEOrN_-f7igqZVHFJnbaWmgCAxkt-vaUlj0

### users
GET http://localhost:3000/v1/user/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTA2OTU3MjEsImV4cCI6MTY1MDY5OTMyMSwiYXVkIjoiNjI2MTU0ZjM4ZjRlNzUwOGI0YzNmOGU0IiwiaXNzIjoiYml4YmFzZS5jb20ifQ.lIjbyyVy71A7Lu8A2d9NipPC9-veuipLapZcZ28Pn_U



### register
POST http://localhost:3000/v1/auth/register
Content-Type: application/json

{
    "email":"chydldafu@gmdail.com",
    "password":"123456789",
    "fullName":"ketem one",
    "mobile":"07057001119"
}


### login
POST http://localhost:3000/v1/auth/login
Content-Type: application/json

{
    "email":"chylau@gmail.com",
    "password":"123456789"
}

 
### refresh token
POST http://localhost:3000/v1/auth/reftk
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTA2OTA3MDUsImV4cCI6MTY4MjI0ODMwNSwiYXVkIjoiNjI2MTU0ZjM4ZjRlNzUwOGI0YzNmOGU0IiwiaXNzIjoiYml4YmFzZS5jb20ifQ.PiPZIrBeWfMDFpUrN29LEsS-BMZNTpEY4p28zdw4-J0"
}



### Logout
POST http://localhost:3000/v1/auth/logout
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTA0NjA0MzcsImV4cCI6MTY4MjAxODAzNywiYXVkIjoiNjI1ZTNhYzc1YTZmNGViMDg4ZjQ4MTRlIiwiaXNzIjoiYml4YmFzZS5jb20ifQ.bx0w4tWT4KsTduaKoOL4Du39rfmBh1dbcaSPxoywBa0"
}
