GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTA1NDU5MDcsImV4cCI6MTY1MDU0OTUwNywiYXVkIjoiNjI2MTU0ZjM4ZjRlNzUwOGI0YzNmOGU0IiwiaXNzIjoiYml4YmFzZS5jb20ifQ.adkY3De3XEOrN_-f7igqZVHFJnbaWmgCAxkt-vaUlj0


### user
GET http://localhost:3000/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTA1NDU5MDcsImV4cCI6MTY1MDU0OTUwNywiYXVkIjoiNjI2MTU0ZjM4ZjRlNzUwOGI0YzNmOGU0IiwiaXNzIjoiYml4YmFzZS5jb20ifQ.adkY3De3XEOrN_-f7igqZVHFJnbaWmgCAxkt-vaUlj0



### register
POST http://localhost:3000/v1/auth/register
Content-Type: application/json

{
    "email":"chylau@gmail.com",
    "password":"123456789",
    "fullName":"ketem one",
    "mobile":"07057001119"
}


### login
POST http://localhost:3000/v1/auth/login
Content-Type: application/json

{
    "email":"chylau@gmail.com",
    "password":"123456789"
}

 
### refresh token
POST http://localhost:3000/v1/auth/reftk
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTA1NDU5MDcsImV4cCI6MTY4MjEwMzUwNywiYXVkIjoiNjI2MTU0ZjM4ZjRlNzUwOGI0YzNmOGU0IiwiaXNzIjoiYml4YmFzZS5jb20ifQ.ikNzu4eWWzob8BI6rrLlp5VvpGCXyOhC6vYHrG8LGJw"
}



### Logout
POST http://localhost:3000/v1/auth/logout
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTA0NjA0MzcsImV4cCI6MTY4MjAxODAzNywiYXVkIjoiNjI1ZTNhYzc1YTZmNGViMDg4ZjQ4MTRlIiwiaXNzIjoiYml4YmFzZS5jb20ifQ.bx0w4tWT4KsTduaKoOL4Du39rfmBh1dbcaSPxoywBa0"
}


### task
POST http://localhost:3000/v1/task/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTA1NDU5MDcsImV4cCI6MTY1MDU0OTUwNywiYXVkIjoiNjI2MTU0ZjM4ZjRlNzUwOGI0YzNmOGU0IiwiaXNzIjoiYml4YmFzZS5jb20ifQ.adkY3De3XEOrN_-f7igqZVHFJnbaWmgCAxkt-vaUlj0
Content-Type: application/json

{
    "project_id":"cdddoy@gail.co",
    "title":"123456789",
    "descriptions":"ketem one",
    "dates":{
        "issueDate":"24/04/14",
        "completeionDate":"26/06/2020"
    }
}

### task
POST http://localhost:3000/v1/task/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTA1NDU5MDcsImV4cCI6MTY1MDU0OTUwNywiYXVkIjoiNjI2MTU0ZjM4ZjRlNzUwOGI0YzNmOGU0IiwiaXNzIjoiYml4YmFzZS5jb20ifQ.adkY3De3XEOrN_-f7igqZVHFJnbaWmgCAxkt-vaUlj0
Content-Type: application/json

{
    "id":"626155c48f4e7508b4c3f8e9"
}


### task
POST http://localhost:3000/v1/task/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTA1NDU5MDcsImV4cCI6MTY1MDU0OTUwNywiYXVkIjoiNjI2MTU0ZjM4ZjRlNzUwOGI0YzNmOGU0IiwiaXNzIjoiYml4YmFzZS5jb20ifQ.adkY3De3XEOrN_-f7igqZVHFJnbaWmgCAxkt-vaUlj0
Content-Type: application/json

{
    "dates": {
      "issueDate": "56777",
      "completeionDate": "26/06/2020"
    },
    "id": "626155c48f4e7508b4c3f8e9",
    "project_id": "coy@gail.co",
    "title": "bolu",
    "descriptions": "ketem og",
    "status": "completed"
}


### task
POST http://localhost:3000/v1/task/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTA1NDU5MDcsImV4cCI6MTY1MDU0OTUwNywiYXVkIjoiNjI2MTU0ZjM4ZjRlNzUwOGI0YzNmOGU0IiwiaXNzIjoiYml4YmFzZS5jb20ifQ.adkY3De3XEOrN_-f7igqZVHFJnbaWmgCAxkt-vaUlj0
Content-Type: application/json

{
    "id":"626155c48f4e7508b4c3f8e9"
}





### project
POST http://localhost:3000/v1/project/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTA1NDU5MDcsImV4cCI6MTY1MDU0OTUwNywiYXVkIjoiNjI2MTU0ZjM4ZjRlNzUwOGI0YzNmOGU0IiwiaXNzIjoiYml4YmFzZS5jb20ifQ.adkY3De3XEOrN_-f7igqZVHFJnbaWmgCAxkt-vaUlj0
Content-Type: application/json

{
    "project_id":"cdddoy@gail.co",
    "title":"123456789",
    "descriptions":"ketem one",
    "dates":{
        "issueDate":"24/04/14",
        "completeionDate":"26/06/2020"
    }
}

### project
POST http://localhost:3000/v1/project/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTA1NDU5MDcsImV4cCI6MTY1MDU0OTUwNywiYXVkIjoiNjI2MTU0ZjM4ZjRlNzUwOGI0YzNmOGU0IiwiaXNzIjoiYml4YmFzZS5jb20ifQ.adkY3De3XEOrN_-f7igqZVHFJnbaWmgCAxkt-vaUlj0
Content-Type: application/json

{
    "id":"626155c48f4e7508b4c3f8e9"
}


### project
POST http://localhost:3000/v1/project/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTA1NDU5MDcsImV4cCI6MTY1MDU0OTUwNywiYXVkIjoiNjI2MTU0ZjM4ZjRlNzUwOGI0YzNmOGU0IiwiaXNzIjoiYml4YmFzZS5jb20ifQ.adkY3De3XEOrN_-f7igqZVHFJnbaWmgCAxkt-vaUlj0
Content-Type: application/json

{
    "dates": {
      "issueDate": "56777",
      "completeionDate": "26/06/2020"
    },
    "id": "626155c48f4e7508b4c3f8e9",
    "project_id": "coy@gail.co",
    "title": "bolu",
    "descriptions": "ketem og",
    "status": "completed"
}



### project
POST http://localhost:3000/v1/project/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTA1NDU5MDcsImV4cCI6MTY1MDU0OTUwNywiYXVkIjoiNjI2MTU0ZjM4ZjRlNzUwOGI0YzNmOGU0IiwiaXNzIjoiYml4YmFzZS5jb20ifQ.adkY3De3XEOrN_-f7igqZVHFJnbaWmgCAxkt-vaUlj0
Content-Type: application/json

{
    "id":"626155c48f4e7508b4c3f8e9"
}